//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce_2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Ecommerce_2Entities : DbContext
    {
        public Ecommerce_2Entities()
            : base("name=Ecommerce_2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<BillingInfo> BillingInfoes { get; set; }
        public virtual DbSet<BranchAddress> BranchAddresses { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Partner> Partners { get; set; }
        public virtual DbSet<personalInfo> personalInfoes { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Shipper> Shippers { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
    
        public virtual ObjectResult<DIRTY_READ_TRANS1_Result> DIRTY_READ_TRANS1(Nullable<int> oRDERID, string aDDRESS)
        {
            var oRDERIDParameter = oRDERID.HasValue ?
                new ObjectParameter("ORDERID", oRDERID) :
                new ObjectParameter("ORDERID", typeof(int));
    
            var aDDRESSParameter = aDDRESS != null ?
                new ObjectParameter("ADDRESS", aDDRESS) :
                new ObjectParameter("ADDRESS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DIRTY_READ_TRANS1_Result>("DIRTY_READ_TRANS1", oRDERIDParameter, aDDRESSParameter);
        }
    
        public virtual ObjectResult<DIRTY_READ_TRANS2_Result> DIRTY_READ_TRANS2(Nullable<int> oRDERID)
        {
            var oRDERIDParameter = oRDERID.HasValue ?
                new ObjectParameter("ORDERID", oRDERID) :
                new ObjectParameter("ORDERID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DIRTY_READ_TRANS2_Result>("DIRTY_READ_TRANS2", oRDERIDParameter);
        }
    
        public virtual ObjectResult<UNREPEATABLE_READ1_Result> UNREPEATABLE_READ1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UNREPEATABLE_READ1_Result>("UNREPEATABLE_READ1");
        }
    
        public virtual int UNREPEATABLE_READ2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UNREPEATABLE_READ2");
        }
    }
}
